
# This file controls the behavior of the Supabase CLI.
# Syntax: https://github.com/toml-lang/toml

project_id = "cahergndkwfqltxyikyr"

[functions.openai-extractor]
verify_jwt = true

[functions.settings]
verify_jwt = true

[functions.test-openai]
verify_jwt = true

[functions.generate-response]
verify_jwt = true

[functions.view-logs]
verify_jwt = true
