
project_id = "cahergndkwfqltxyikyr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions.generate-document]
verify_jwt = true

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true
