
project_id = "cahergndkwfqltxyikyr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[functions]
[functions.email-receiver]
verify_jwt = false

[functions.invoice-receiver]
verify_jwt = false

[functions.homeowner-request-email]
verify_jwt = false

[auth]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[studio]
enabled = true
port = 54323
