
# A string used to distinguish different Supabase projects on the same host. Defaults to the project ID.
project_id = "cahergndkwfqltxyikyr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[storage]
enabled = true
port = 54327

[experimental.functions]
enabled = true
port = 54328

# Disable JWT verification for webhook functions
[experimental.functions.email-receiver]
verify_jwt = false

[experimental.functions.invoice-receiver]
verify_jwt = false

[experimental.functions.homeowner-request-email]
verify_jwt = false

[experimental.functions.test-webhook]
verify_jwt = false

[experimental.functions.test-auth]
verify_jwt = false
