
project_id = "cahergndkwfqltxyikyr"

[api]
enabled = true

[db]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.invoice-receiver]
verify_jwt = false
[functions.pdf-proxy]
verify_jwt = false
