
import { Property } from '@/pages/Properties';

export const mockProperties: Property[] = [
  {
    id: 'PROP-101',
    address: '123 Oak Lane',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    type: 'single-family',
    bedrooms: 4,
    bathrooms: 3,
    sqFt: 2400,
    association: 'Oakridge Estates',
    associationId: 'assoc-001',
    status: 'occupied',
    ownerName: 'Michael Thompson'
  },
  {
    id: 'PROP-102',
    address: '456 Maple Street',
    city: 'Austin',
    state: 'TX',
    zip: '78702',
    type: 'townhouse',
    bedrooms: 3,
    bathrooms: 2.5,
    sqFt: 1800,
    association: 'Oakridge Estates',
    associationId: 'assoc-001',
    status: 'occupied',
    ownerName: 'Sarah Johnson'
  },
  {
    id: 'PROP-103',
    address: '789 Pine Avenue',
    city: 'Austin',
    state: 'TX',
    zip: '78703',
    type: 'condo',
    bedrooms: 2,
    bathrooms: 2,
    sqFt: 1200,
    association: 'Highland Towers',
    associationId: 'assoc-002',
    status: 'vacant'
  },
  {
    id: 'PROP-104',
    address: '101 Elm Court',
    city: 'Austin',
    state: 'TX',
    zip: '78704',
    type: 'single-family',
    bedrooms: 5,
    bathrooms: 3.5,
    sqFt: 3200,
    association: 'Lakeside Community',
    associationId: 'assoc-003',
    status: 'occupied',
    ownerName: 'David Wilson'
  },
  {
    id: 'PROP-105',
    address: '202 Cedar Road',
    city: 'Austin',
    state: 'TX',
    zip: '78705',
    type: 'townhouse',
    bedrooms: 3,
    bathrooms: 2,
    sqFt: 1750,
    association: 'Lakeside Community',
    associationId: 'assoc-003',
    status: 'delinquent',
    ownerName: 'Jennifer Miller'
  },
  {
    id: 'PROP-106',
    address: '303 Birch Drive',
    city: 'Austin',
    state: 'TX',
    zip: '78705',
    type: 'condo',
    bedrooms: 1,
    bathrooms: 1,
    sqFt: 850,
    association: 'Highland Towers',
    associationId: 'assoc-002',
    status: 'pending',
  },
];
