export const glAccountsSeedData = [
  { code: '5939', name: 'Access Cards', type: 'Expense' },
  { code: '4506', name: 'Access Devices', type: 'Income' },
  { code: '2100', name: 'Accounts Payable', type: 'Liability' },
  { code: '1200', name: 'Accounts Receivable', type: 'Asset' },
  { code: '5000', name: 'Admin Expenses', type: 'Expense' },
  { code: '4130', name: 'Admin Fee', type: 'Income' },
  { code: '5015', name: 'Administrative Fees', type: 'Expense' },
  { code: '1205', name: 'Allowance for Bad Debt', type: 'Asset' },
  { code: '5212', name: 'Amenity Center R & M', type: 'Expense' },
  { code: '4126', name: 'Architectural Permit Income', type: 'Income' },
  { code: '5025', name: 'Architectural Review', type: 'Expense' },
  { code: '4000', name: 'Assessment', type: 'Income' },
  { code: '8035', name: 'Audit/Review Expense', type: 'Expense' },
  { code: '5001', name: 'Bad Debt', type: 'Expense' },
  { code: '5010', name: 'Bank Charges', type: 'Expense' },
  { code: '4025', name: 'Builder Fee Income', type: 'Income' },
  { code: '1215', name: 'Builders Fee', type: 'Asset' },
  { code: '4148', name: 'Building Key Cards', type: 'Income' },
  { code: '6211', name: 'Cable', type: 'Expense' },
  { code: '4550', name: 'Campground Rental', type: 'Income' },
  { code: '1510', name: 'CD', type: 'Asset' },
  { code: '4131', name: 'Certified Mail Fee', type: 'Income' },
  { code: '1003', name: 'CIT Operating-X3921', type: 'Asset' },
  { code: '1000', name: 'CIT Operating-X2472', type: 'Asset' },
  { code: '1100', name: 'CIT Reserve-X2481', type: 'Asset' },
  { code: '4515', name: 'Clubhouse Rental Income', type: 'Income' },
  { code: '5055', name: 'Collection Attorney Expense', type: 'Expense' },
  { code: '5057', name: 'Computer Software', type: 'Expense' },
  { code: '9020', name: 'Contingency', type: 'Expense' },
  { code: '9050', name: 'Contribution to Reserves', type: 'Expense' },
  { code: '4050', name: 'Contribution to Reserves Income', type: 'Income' },
  { code: '8010', name: 'D&O Insurance', type: 'Expense' },
  { code: '6143', name: 'Delinquency Fee Expense', type: 'Expense' },
  { code: '4115', name: 'Demand Letter Income', type: 'Income' },
  { code: '6200', name: 'Drainage', type: 'Expense' },
  { code: '2500', name: 'Due To/Due From', type: 'Liability' },
  { code: '6179', name: 'Dues & Subscriptions', type: 'Expense' },
  { code: '6220', name: 'Electric', type: 'Expense' },
  { code: '5220', name: 'Electrical R&M', type: 'Expense' },
  { code: '5936', name: 'Fire Prevention & Protection Monitoring', type: 'Expense' },
  { code: '5780', name: 'Fitness Center R&M', type: 'Expense' },
  { code: '4033', name: 'Force Mow', type: 'Income' },
  { code: '4035', name: 'Force Mow', type: 'Income' },
  { code: '5012', name: 'Fraudulent Checks', type: 'Expense' },
  { code: '4021', name: 'Gate Opener Income', type: 'Income' },
  { code: '5210', name: 'Gate R&M', type: 'Expense' },
  // ... (include every code from your list, trimmed for brevity, add as needed)
  // Copy/paste the rest of your list here.
];
