-- Add ai_confidence column to leads table if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'leads' AND column_name = 'ai_confidence'
  ) THEN
    ALTER TABLE public.leads ADD COLUMN ai_confidence JSONB;
  END IF;
END$$;

-- Track which fields were generated by AI
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'leads' AND column_name = 'ai_generated_fields'
  ) THEN
    ALTER TABLE public.leads ADD COLUMN ai_generated_fields TEXT[];
  END IF;
END$$;
