name: Deploy to Supabase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy homeowner-request-email function to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ] || [ -z "$SUPABASE_PROJECT_ID" ]; then
            echo "Supabase secrets are not set. Please add SUPABASE_ACCESS_TOKEN and SUPABASE_PROJECT_ID to your repository secrets."
            exit 1
          fi
          
          supabase functions deploy homeowner-request-email \
            --project-ref "$SUPABASE_PROJECT_ID" \
            --no-verify-jwt
